---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements.yml
    requirements-file: collections.yml

driver:
  name: docker

platforms:
  - name: docker-ubuntu2004-ansible
    image: geerlingguy/docker-ubuntu2004-ansible
    exposed_ports:
      - 80/tcp
      - 443/tcp
    published_ports:
      - 0.0.0.0:80:80/tcp
      - 0.0.0.0:443:443/tcp
      - 0.0.0.0:222:22/tcp
      - 0.0.0.0:873:873/tcp
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /dev/null:/dev/null:rw
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:

  name: ansible
  config_options:
    defaults:
      vault_password_file: ${MOLECULE_PROJECT_DIRECTORY}/../.vault_password

  inventory:
    host_vars:
      docker-ubuntu2004-ansible:
        ansible_user: root

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
